toolbar:
  - undo redo | styleselect | image media link codesample | forecolor backcolor | numlist bullist | table | code | preview
plugins:
  - image
  - media
  - link
  - table
  - codesample
  - textcolor
  - code
  - hr
  - lists
  - wordcount
  - preview